### ISSUE TITLE
ssl instrutions

### ISSUE THREAD

**Issue by laznick** [daxAKAhackerman/XSS-Catcher#154]
Hey, is it possible you could include instruction on setting this up with SSL certifcate? thanks.

**Comment by daxAKAhackerman** [comment]
Hi 👋 While SSL/TLS certification configuration isn't really in scope of this project, I'll gladly point you in the right direction! 

Personally, I find that using NGINX as a reverse proxy with letsencrypt for certificate generation is a pretty simple setup that works well. If you are not familiar with a reverse proxy, it's basically a web server that will route requests to other servers and will usually take care of certificates and general server configuration such as security headers. 

The following `gist` gives a nice condensed explanation on how to set this up, just don't forget to swap port `8080` in the example for port `8888`, which is the one that is used by XSS Catcher: https://gist.github.com/gmolveau/5e5b0bd2773100d85d9302d0fa96632d. Of course this tutorial assumes that your HTTPS port (443) is exposed to the internet, so don't forget to setup any needed port-forwarding if doing the setup from home!

**Comment by daxAKAhackerman** [comment]
Closing the issue, but don't hesitate to re-open if you have anymore questions!
