### ISSUE TITLE
Default credentials aren't working

### ISSUE THREAD

**Issue by NBanski** [daxAKAhackerman/XSS-Catcher#18]
Hello, 
as for now, it seems that default creds to web panel are not working (admin:xss). 
More so, sending any POST request via login panel returns internal server error (500).

**Comment by daxAKAhackerman** [comment]
Weird 🤔  Did you run the `make deploy` command as instructed in the README? If so, did it throw any error? You could also run the `docker logs` command with the XSS Catcher container names to see if there was any error while starting the containers.

**Comment by NBanski** [comment]
Yes, I believe I've done everything as you described in the readme. All containers seem to be running fine, but there may be a problem with backend server. All error logs server boil down to problems with Flask/SQLAlchemy.

If you want to look at full error codes, here there are:
https://pastebin.pl/view/57d56cb9

**Comment by NBanski** [comment]
I've fixed it and created a pull request.

**Comment by daxAKAhackerman** [comment]
Fixed in release v1.4.1
