### ISSUE TITLE
Add slack notification

### ISSUE THREAD

**Issue by Serizao** [daxAKAhackerman/XSS-Catcher#21]
Hello thank you so much for this tools it's very useful :)

Do you think it's possible to integrate slack notification ?

Thank's

**Comment by daxAKAhackerman** [comment]
I've started working on it in the [feature branch](/daxAKAhackerman/XSS-Catcher/tree/feat/webhook_support).

**Comment by Serizao** [comment]
Niiice :D thank you so much

**Comment by daxAKAhackerman** [comment]
The feature is now merged to the main branch 🎉 To update, run `git pull && make update`. The following procedure can be followed to generate a Slack webhook URL: https://api.slack.com/messaging/webhooks
