### ISSUE TITLE
Default credentials failing

### ISSUE THREAD

**Issue by xnl-h4ck3r** [daxAKAhackerman/XSS-Catcher#23]
Hi. The default credentials of admin:xss did not work. After looking at the logs there is a database error when the admin user was added. The error was "value too long for type character varying(95)" and seems to be for the password_hash field.
The password_hash value it tried to add on setup was 102 characters (7 characters over) and started with "pbkdf2:sha256:260000$"

**Comment by daxAKAhackerman** [comment]
Yep you are completely right. Not sure why the hash doesn't fit in the db field anymore though 🤔 It is already fixed in the feature branch, but I will release a quick patch right now 😄

**Comment by daxAKAhackerman** [comment]
Fixed in v1.6.1 🙂 Thanks for the issue!

**Comment by xnl-h4ck3r** [comment]
Thanks for fixing it so quick! All working now :)
