### ISSUE TITLE
Add Discord Webhooks for notification

### ISSUE THREAD

**Issue by vermsec** [daxAKAhackerman/XSS-Catcher#25]
Hi,
Thank you for the tool, it works perfectly!

I see we have Slack webhook implemented for notification, is it possible to have the same for discord?

**Comment by daxAKAhackerman** [comment]
Hey 👋  I just tested it on Discord and since it supports Slack message format, it works out of the box 🙂  Just append `/slack` to your Discord webhook URL and add it to your XSS-Catcher settings (or client settings) and you should be good to go!

**Comment by vermsec** [comment]
Thanks a bunch it works!
