### ISSUE TITLE
Set Domain?

### ISSUE THREAD

**Issue by Xhar0l** [daxAKAhackerman/XSS-Catcher#27]
Is there a way to set my own domain for the .js?

**Comment by daxAKAhackerman** [comment]
The `collector.js` script is hosted under the same domain as the XSS Catcher application. However, you could technically take the `client/public/scripts/collector.js` file, host it anywhere you want and just swap out the URL in the XSS payload, and it should still work.

**Comment by daxAKAhackerman** [comment]
Closing since no answer for over a week, feel free to re-open if you have further questions!
