### ISSUE TITLE
python3 module error

### ISSUE THREAD

**Issue by gprime31** [daxAKAhackerman/XSS-Catcher#31]
![2022-02-25_06-09](https://user-images.githubusercontent.com/44535257/155705420-2437661c-0ec3-494e-aa3b-78caf7a8415a.png)
after running:
docker logs xss-catcher_backend_1
fresh install

**Comment by daxAKAhackerman** [comment]
Hello again @gprime31 👋 

It seems that the last minor update of one of my dependencies broke Flask (itsdangerous v2.0.1 -> v2.1.0). 

I fixed the working version in the requirements and did the same with every dependencies to prevent this issue from happening again. 

Just pull the latest version that I just released (https://github.com/daxAKAhackerman/XSS-Catcher/releases/tag/v1.8.1) and run `make update` and you should be good to go!

**Comment by gprime31** [comment]
Awesome as always!
Thanks
