### ISSUE TITLE
XSS payload generator

### ISSUE THREAD

**Issue by Brainmoustache** [daxAKAhackerman/XSS-Catcher#7]
When generating a payload, there is a visual issue. The following screenshot illustrates the bug:

![bugg](https://user-images.githubusercontent.com/32066865/76868172-e656dc00-683c-11ea-9582-d182dbf03a4a.png)

**Comment by daxAKAhackerman** [comment]
Fixed in commit 9eb53efbcf3c4e1f089e1d4206be297149967572
